WORKBENCH_NAME = "ParamWeave"
DOCK_OBJECT_NAME = "ParamWeave_Dock"
STORE_OBJECT_NAME = "ParamWeaveGraph"
GENERATED_GROUP_NAME = "ParamWeave_Generated"
NODE_ID_PROPERTY = "ParamWeaveNodeId"
REFERENCE_NODE_TYPE = "reference.geometry"
